language: python
python:
- 2.7
branches:
  only:
  - master
  - develop
  - develop-proto
script:
- nosetests -v $VIRTUAL_ENV/src/avro-schema-test-base
notifications:
  slack:
    secure: RmyIMB6tA868r+dHECJ566r0+TCB6pHvg9PygNiM5ye+iX4I+CFKMoGzjeMVtuLI80MSzzoaB+PU6TczlhzdbJBALqiV74AQCoNGqswJzJCkJX7HDGk8LVFSsnpwClRLLLVgvBApGDS0ViRfGqsew8CJ8VR5BMDiU53z3Of4JHc=
